# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1719, 605)
        self.funcArea = QtWidgets.QGroupBox(Form)
        self.funcArea.setGeometry(QtCore.QRect(10, 0, 261, 141))
        self.funcArea.setObjectName("funcArea")
        self.layoutWidget = QtWidgets.QWidget(self.funcArea)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 261, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.betteryBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.betteryBar.setProperty("value", 24)
        self.betteryBar.setObjectName("betteryBar")
        self.gridLayout.addWidget(self.betteryBar, 2, 1, 1, 1)
        self.rssi = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        self.rssi.setFont(font)
        self.rssi.setObjectName("rssi")
        self.gridLayout.addWidget(self.rssi, 0, 0, 1, 1)
        self.rssiBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.rssiBar.setProperty("value", 24)
        self.rssiBar.setObjectName("rssiBar")
        self.gridLayout.addWidget(self.rssiBar, 0, 1, 1, 1)
        self.rssi_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        self.rssi_2.setFont(font)
        self.rssi_2.setObjectName("rssi_2")
        self.gridLayout.addWidget(self.rssi_2, 2, 0, 1, 1)
        self.btnGroup = QtWidgets.QGroupBox(Form)
        self.btnGroup.setGeometry(QtCore.QRect(320, 0, 261, 141))
        self.btnGroup.setObjectName("btnGroup")
        self.connectBtn = QtWidgets.QPushButton(self.btnGroup)
        self.connectBtn.setGeometry(QtCore.QRect(10, 20, 111, 51))
        self.connectBtn.setObjectName("connectBtn")
        self.disConnectBtn = QtWidgets.QPushButton(self.btnGroup)
        self.disConnectBtn.setGeometry(QtCore.QRect(130, 20, 111, 51))
        self.disConnectBtn.setObjectName("disConnectBtn")
        self.startBtn = QtWidgets.QPushButton(self.btnGroup)
        self.startBtn.setGeometry(QtCore.QRect(10, 80, 111, 51))
        self.startBtn.setObjectName("startBtn")
        self.saveBtn = QtWidgets.QPushButton(self.btnGroup)
        self.saveBtn.setGeometry(QtCore.QRect(130, 80, 111, 51))
        self.saveBtn.setObjectName("saveBtn")
        self.msgGroup = QtWidgets.QGroupBox(Form)
        self.msgGroup.setGeometry(QtCore.QRect(1450, 0, 261, 591))
        self.msgGroup.setObjectName("msgGroup")
        self.msgBrowser = QtWidgets.QTextBrowser(self.msgGroup)
        self.msgBrowser.setGeometry(QtCore.QRect(10, 20, 241, 521))
        self.msgBrowser.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.msgBrowser.setObjectName("msgBrowser")
        self.label = QtWidgets.QLabel(self.msgGroup)
        self.label.setGeometry(QtCore.QRect(60, 560, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.plotGroup = QtWidgets.QGroupBox(Form)
        self.plotGroup.setGeometry(QtCore.QRect(590, 0, 851, 591))
        self.plotGroup.setObjectName("plotGroup")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.plotGroup)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 831, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.graph_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.graph_layout.setContentsMargins(0, 0, 0, 0)
        self.graph_layout.setObjectName("graph_layout")
        self.setWidget = QtWidgets.QTabWidget(Form)
        self.setWidget.setGeometry(QtCore.QRect(10, 150, 571, 361))
        self.setWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.setWidget.setToolTip("")
        self.setWidget.setObjectName("setWidget")
        self.initSet = QtWidgets.QWidget()
        self.initSet.setObjectName("initSet")
        self.skipBtn = QtWidgets.QPushButton(self.initSet)
        self.skipBtn.setGeometry(QtCore.QRect(340, 140, 151, 61))
        self.skipBtn.setObjectName("skipBtn")
        self.openDir = QtWidgets.QPushButton(self.initSet)
        self.openDir.setGeometry(QtCore.QRect(20, 140, 141, 61))
        self.openDir.setObjectName("openDir")
        self.setWidget.addTab(self.initSet, "")
        self.tGes = QtWidgets.QWidget()
        self.tGes.setObjectName("tGes")
        self.tLabel = QtWidgets.QLabel(self.tGes)
        self.tLabel.setGeometry(QtCore.QRect(180, 20, 195, 260))
        self.tLabel.setAccessibleName("")
        self.tLabel.setText("")
        self.tLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.tLabel.setObjectName("tLabel")
        self.remindLabel = QtWidgets.QLabel(self.tGes)
        self.remindLabel.setGeometry(QtCore.QRect(160, 290, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.remindLabel.setFont(font)
        self.remindLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.remindLabel.setObjectName("remindLabel")
        self.setWidget.addTab(self.tGes, "")
        self.xGes = QtWidgets.QWidget()
        self.xGes.setObjectName("xGes")
        self.xLabel = QtWidgets.QLabel(self.xGes)
        self.xLabel.setGeometry(QtCore.QRect(180, 20, 195, 260))
        self.xLabel.setText("")
        self.xLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xLabel.setObjectName("xLabel")
        self.setWidget.addTab(self.xGes, "")
        self.kGes = QtWidgets.QWidget()
        self.kGes.setObjectName("kGes")
        self.kLabel = QtWidgets.QLabel(self.kGes)
        self.kLabel.setGeometry(QtCore.QRect(180, 20, 195, 260))
        self.kLabel.setText("")
        self.kLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kLabel.setObjectName("kLabel")
        self.setWidget.addTab(self.kGes, "")
        self.pGes = QtWidgets.QWidget()
        self.pGes.setObjectName("pGes")
        self.pLabel = QtWidgets.QLabel(self.pGes)
        self.pLabel.setGeometry(QtCore.QRect(180, 20, 195, 260))
        self.pLabel.setText("")
        self.pLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pLabel.setObjectName("pLabel")
        self.setWidget.addTab(self.pGes, "")
        self.adGes = QtWidgets.QWidget()
        self.adGes.setObjectName("adGes")
        self.adLabel = QtWidgets.QLabel(self.adGes)
        self.adLabel.setGeometry(QtCore.QRect(180, 20, 195, 260))
        self.adLabel.setText("")
        self.adLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.adLabel.setObjectName("adLabel")
        self.setWidget.addTab(self.adGes, "")
        self.abGes = QtWidgets.QWidget()
        self.abGes.setObjectName("abGes")
        self.abLabel = QtWidgets.QLabel(self.abGes)
        self.abLabel.setGeometry(QtCore.QRect(180, 20, 195, 260))
        self.abLabel.setText("")
        self.abLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.abLabel.setObjectName("abLabel")
        self.setWidget.addTab(self.abGes, "")
        self.gGes = QtWidgets.QWidget()
        self.gGes.setObjectName("gGes")
        self.gLabel = QtWidgets.QLabel(self.gGes)
        self.gLabel.setGeometry(QtCore.QRect(180, 20, 195, 260))
        self.gLabel.setText("")
        self.gLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gLabel.setObjectName("gLabel")
        self.setWidget.addTab(self.gGes, "")
        self.fGes = QtWidgets.QWidget()
        self.fGes.setObjectName("fGes")
        self.fLabel = QtWidgets.QLabel(self.fGes)
        self.fLabel.setGeometry(QtCore.QRect(180, 20, 195, 260))
        self.fLabel.setText("")
        self.fLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fLabel.setObjectName("fLabel")
        self.setWidget.addTab(self.fGes, "")
        self.iGes = QtWidgets.QWidget()
        self.iGes.setObjectName("iGes")
        self.iLabel = QtWidgets.QLabel(self.iGes)
        self.iLabel.setGeometry(QtCore.QRect(180, 20, 195, 260))
        self.iLabel.setText("")
        self.iLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.iLabel.setObjectName("iLabel")
        self.setWidget.addTab(self.iGes, "")
        self.oGes = QtWidgets.QWidget()
        self.oGes.setObjectName("oGes")
        self.oLabel = QtWidgets.QLabel(self.oGes)
        self.oLabel.setGeometry(QtCore.QRect(180, 20, 195, 260))
        self.oLabel.setText("")
        self.oLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.oLabel.setObjectName("oLabel")
        self.setWidget.addTab(self.oGes, "")
        self.vGes = QtWidgets.QWidget()
        self.vGes.setObjectName("vGes")
        self.vLabel = QtWidgets.QLabel(self.vGes)
        self.vLabel.setGeometry(QtCore.QRect(180, 20, 195, 260))
        self.vLabel.setText("")
        self.vLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.vLabel.setObjectName("vLabel")
        self.setWidget.addTab(self.vGes, "")
        self.rGes = QtWidgets.QWidget()
        self.rGes.setObjectName("rGes")
        self.rLabel = QtWidgets.QLabel(self.rGes)
        self.rLabel.setGeometry(QtCore.QRect(180, 20, 195, 260))
        self.rLabel.setText("")
        self.rLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rLabel.setObjectName("rLabel")
        self.setWidget.addTab(self.rGes, "")
        self.trainSet = QtWidgets.QWidget()
        self.trainSet.setObjectName("trainSet")
        self.trainBtn = QtWidgets.QPushButton(self.trainSet)
        self.trainBtn.setGeometry(QtCore.QRect(60, 140, 131, 51))
        self.trainBtn.setObjectName("trainBtn")
        self.trainLabel = QtWidgets.QLabel(self.trainSet)
        self.trainLabel.setGeometry(QtCore.QRect(270, 230, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.trainLabel.setFont(font)
        self.trainLabel.setText("")
        self.trainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trainLabel.setObjectName("trainLabel")
        self.predictBtn = QtWidgets.QPushButton(self.trainSet)
        self.predictBtn.setGeometry(QtCore.QRect(290, 140, 131, 51))
        self.predictBtn.setObjectName("predictBtn")
        self.setWidget.addTab(self.trainSet, "")
        self.nextBtn = QtWidgets.QPushButton(Form)
        self.nextBtn.setGeometry(QtCore.QRect(440, 530, 131, 51))
        self.nextBtn.setObjectName("nextBtn")
        self.againBtn = QtWidgets.QPushButton(Form)
        self.againBtn.setGeometry(QtCore.QRect(10, 530, 121, 51))
        self.againBtn.setObjectName("againBtn")
        self.codeLabel = QtWidgets.QLabel(Form)
        self.codeLabel.setGeometry(QtCore.QRect(190, 520, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.codeLabel.setFont(font)
        self.codeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.codeLabel.setObjectName("codeLabel")

        self.retranslateUi(Form)
        self.setWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.funcArea.setTitle(_translate("Form", "Bar"))
        self.rssi.setText(_translate("Form", "RSSI:"))
        self.rssi_2.setText(_translate("Form", "BETTERY:"))
        self.btnGroup.setTitle(_translate("Form", "Func"))
        self.connectBtn.setText(_translate("Form", "Connect"))
        self.disConnectBtn.setText(_translate("Form", "Disconnect"))
        self.startBtn.setText(_translate("Form", "Start"))
        self.saveBtn.setText(_translate("Form", "Save"))
        self.msgGroup.setTitle(_translate("Form", "Info"))
        self.label.setText(_translate("Form", "Press ALT to save data"))
        self.plotGroup.setTitle(_translate("Form", "sEMG"))
        self.skipBtn.setText(_translate("Form", "Skip Train"))
        self.openDir.setText(_translate("Form", "Default Dir"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.initSet), _translate("Form", "Initial Setting"))
        self.remindLabel.setText(_translate("Form", "Please press Connect & Start to begain"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.tGes), _translate("Form", "t"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.xGes), _translate("Form", "x"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.kGes), _translate("Form", "k"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.pGes), _translate("Form", "p"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.adGes), _translate("Form", "ad"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.abGes), _translate("Form", "ab"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.gGes), _translate("Form", "g"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.fGes), _translate("Form", "f"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.iGes), _translate("Form", "i"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.oGes), _translate("Form", "o"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.vGes), _translate("Form", "v"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.rGes), _translate("Form", "r"))
        self.trainBtn.setText(_translate("Form", "Train"))
        self.predictBtn.setText(_translate("Form", "Ready to Predict"))
        self.setWidget.setTabText(self.setWidget.indexOf(self.trainSet), _translate("Form", "train"))
        self.nextBtn.setText(_translate("Form", "Next"))
        self.againBtn.setText(_translate("Form", "ReSave Last Sample"))
        self.codeLabel.setText(_translate("Form", "GO MYO"))
